debug_listen_port: 8000
debug_mode: False
root_path: '/something'
log_level: DEBUG
secret: 'your_secret'
projects:
  -
    repo_name: 'User/repo-name'
    repo_path: '/absolute/path/to/repo'
    deploy_branch: 'main'
    user: 'user1'
    commands:
      - '/absolute/path/to/command.sh'
