debug_listen_port: 8000
debug_mode: False
root_path: '/something'
log_level: DEBUG
secret: 'your_secret'
projects:
  -
    repo_name: 'User/repo-name'
    deploy_branch: 'main'
    command: '/absolute/path/to/command.sh'
